### ISSUE TITLE
Add Stox (STX)

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#317]
Currency name: Stox
Symbol: STX
Website: https://www.stox.com
Theme color: `#7020f0`
Logo (SVG): [stox.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3306729/stox.zip)

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
