### ISSUE TITLE
Unus Sed LEO (LEO)

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#326]
Currency name: Unus Sed LEO
Symbol: LEO
Website: https://www.bitfinex.com/, [https://leo.bitfinex.com](https://leo.bitfinex.com/)
Theme color: `#11021E`
Logo (SVG): [UNUS-SED-LEO.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3328894/UNUS-SED-LEO.zip)

**Comment by sindresorhus** [comment]
Can you link to its website, not a trading platform?

**Comment by Paulsky** [comment]
I don't think there is a dedicated website for it (yet). [CoinMarketCap](https://coinmarketcap.com/currencies/unus-sed-leo/) and [CoinGecko](https://www.coingecko.com/en/coins/leo-token?utm_content=leo-token&utm_medium=search_coin&utm_source=coingecko) for example also use the https://www.bitfinex.com link. 

Would this link be suitable...? [https://support.bitfinex.com/hc/en-us/articles/360023617554-Unus-Sed-LEO-Token-Conversion](https://support.bitfinex.com/hc/en-us/articles/360023617554-Unus-Sed-LEO-Token-Conversion)

**Comment by sindresorhus** [comment]
The name is also incorrect. Should be `Unus Sed LEO`.

**Comment by Paulsky** [comment]
Oh sorry, I used the same name as [CoinMarketCap](https://coinmarketcap.com/currencies/unus-sed-leo/) uses.

**Comment by tommdn** [comment]
Done.
