### ISSUE TITLE
Add Half Life (NUKE)

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#328]
Currency name: Half Life
Symbol: NUKE
Website: https://nuketoken.com/
Theme color: `#ddb829`
Logo (SVG): [half-life-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3386496/half-life-logo.zip)

**Comment by sindresorhus** [comment]
I don’t see “half life” mentioned on the website.

**Comment by Paulsky** [comment]
Yeah, I also doubted about the name. But I checked:

- CoinGecko: [https://www.coingecko.com/nl/coins/half-life](https://www.coingecko.com/nl/coins/half-life) (if you follow 'website', you will land on their website)
- Their Twitter [https://twitter.com/NukeToken](https://twitter.com/NukeToken) and I saw 'Half Life'
- And if you follow the link 'etherscan' in the header on their website, you will see 'Token: Half Life'

**Comment by sindresorhus** [comment]
Ok
