### ISSUE TITLE
Add SINOVATE (SIN)

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#330]
Currency name: SINOVATE
Symbol: SIN
Website: https://sinovate.io
Theme color: `#f5342e`
Logo (SVG): [sinovate.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3390077/sinovate.zip)

**Comment by sindresorhus** [comment]
Please follow the issue instructions:

> Ensure the SVG file is a proper vector file and not just embedding a PNG/JPEG file. If the SVG source contains `data:image/png;base64`/`data:image/jpeg;base64` it's not a valid vectorized SVG file.

**Comment by Paulsky** [comment]
My apologies! Please see the new version I uploaded. Hopefully this one is correct.

**Comment by Paulsky** [comment]
Hello @sindresorhus, is the new version correct?

**Comment by sindresorhus** [comment]
Yes

**Comment by Paulsky** [comment]
Thanks @sindresorhus

**Comment by tommdn** [comment]
Done.
