### ISSUE TITLE
Update Chainlink (LINK)

### ISSUE THREAD

**Issue by kursatduygulu** [spothq/cryptocurrency-icons#334]
Currency name: Chainlink
Symbol: LINK
Website: https://chain.link/
Theme color: `#2a5ada`
Logo (SVG): [chainlink-logo-svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3422087/chainlink-logo-svg.zip)

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
