### ISSUE TITLE
Update Tron (TRX)

### ISSUE THREAD

**Issue by srdante** [spothq/cryptocurrency-icons#340]
The icon colors here are black while they were actually supposed to be red.

Currency name: **Tron**
Symbol: **TRX**
Website: https://tron.network/
Theme color: `#C83027`
Logo (SVG): **It's already here.**

**Comment by sindresorhus** [comment]
The color you have provided is not correct either. https://s3.amazonaws.com/tron.network/VISUAL+IDENTITY+GUIDE.pdf

**Comment by srdante** [comment]
So the correct color is `#DC062B`

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
