### ISSUE TITLE
Add Algorand (ALGO)

### ISSUE THREAD

**Issue by bchoubert** [spothq/cryptocurrency-icons#341]
Currency name: Algorand
Symbol: ALGO
Website: https://www.algorand.com/
Theme color: #000000
Logo (SVG): [algorand.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3522119/algorand.zip)

**Comment by Slurpgoose** [comment]
I created these for my project incase anyone needs a temporary fix until the next release

images as png 128px

![algo_colored](https://user-images.githubusercontent.com/41924288/81492852-5e53e800-9269-11ea-8aef-dcdffebf7355.png)
![algo_white](https://user-images.githubusercontent.com/41924288/81492853-5eec7e80-9269-11ea-9c3c-eb9b5228be7a.png)
![algo](https://user-images.githubusercontent.com/41924288/81492854-5eec7e80-9269-11ea-80e3-41b1cebf004e.png)

[algo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/4605264/algo.zip)

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
