### ISSUE TITLE
Update Horizen (ZEN)

### ISSUE THREAD

**Issue by ldevalliere** [spothq/cryptocurrency-icons#345]
Currency name: Horizen
Symbol: ZEN
Website: https://www.horizen.global/
Theme color: #0e9de5
Logo (SVG): [Horizen_logos_SVG.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3547334/Horizen_logos_SVG.zip)

**Comment by sindresorhus** [comment]
What's to update? We already updated it last year: https://github.com/atomiclabs/cryptocurrency-icons/issues/237

**Comment by sindresorhus** [comment]
// @bagintz

**Comment by tommdn** [comment]
Hello @ldevalliere I'm in charge of this repo now and looking at this—is this issue still relevant? If not please provide me with the current SVG file and color. Thank you.

**Comment by ldevalliere** [comment]
Yes, still relevant. 

Issue: https://github.com/spothq/cryptocurrency-icons/blob/master/svg/color/zen.svg is not in color.
Solution: "Horizen_logomark.svg" inside of the zip file in top comment provided above is in color.

**Comment by tommdn** [comment]
Done.
