### ISSUE TITLE
Add BTU (BTU)

### ISSUE THREAD

**Issue by flerunigo** [spothq/cryptocurrency-icons#346]
Currency name: BTU
Symbol: BTU
Website: https://btu-protocol.com
Theme color: #a47fb7
Logo (SVG): https://btu-protocol.com/images/tokenBTU.svg

**Comment by Paulsky** [comment]
Hello @flerunigo, I'm trying to help you out here. You are supposed to upload the SVG icon in a .zip file. I think these should be the correct values:

Add BTU Protocol (BTU)




Currency name: BTU Protocol
Symbol: BTU
Website: https://www.btu-protocol.com/
Theme color: `#007bff`
Logo (SVG): [BTU-Protocol-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3552168/BTU-Protocol-logo.zip)

**Comment by flerunigo** [comment]
Hello @Paulsky. Indeed these are the correct values. Sorry for not zipping the icon.

**Comment by Paulsky** [comment]
@flerunigo No worries, just wanted to help you out!

**Comment by tommdn** [comment]
@flerunigo There is no circle on the website around the icon. Should we keep it or not? If not do you have an updated SVG file? Also which is the correct color? Thank you.

**Comment by tommdn** [comment]
@flerunigo Any news on this?

**Comment by tommdn** [comment]
Closed for lack of activity.
