### ISSUE TITLE
Add Ampleforth (AMPL)

### ISSUE THREAD

**Issue by brandoniles** [spothq/cryptocurrency-icons#353]
Currency name: Ampleforth
Symbol: AMPL
Website: https://ampleforth.org
Theme color: `#000000`
Logo (SVG):
[Ampleforth_Logos.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3773401/Ampleforth_Logos.zip)

**Comment by tommdn** [comment]
@brandoniles I am not sure we can do full white regarding the `color` version, as it would not be readable on white backgrounds—there will be a `white` version anyway, but for the `color` variant do you have a light gray I could use?

**Comment by brandoniles** [comment]
Sure no problem. Can you use 0x000000 for black or will that run into the same problem in reverse?

**Comment by tommdn** [comment]
@brandoniles `#000000` is good.

**Comment by brandoniles** [comment]
Updated the top-level issue. Thanks!

**Comment by tommdn** [comment]
Done.
