### ISSUE TITLE
Rename DAI to SAI

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#358]
Please rename the current Dai (DAI) icon to Sai (SAI).

'Multi-Collateral DAI has launched, SAI refers to the old single collateralized DAI. For the new MCD Dai, refer to https://www.coingecko.com/en/coins/dai'

Please see:
https://www.coingecko.com/en/coins/sai

And:
https://blog.makerdao.com/single-collateral-dai-to-multi-collateral-dai-upgrade-timeline-and-actions/

**Comment by tommdn** [comment]
Done.
