### ISSUE TITLE
Add Dai (DAI)

### ISSUE THREAD

**Issue by Paulsky** [spothq/cryptocurrency-icons#359]
Currency name: Dai
Symbol: DAI
Website: https://makerdao.com/en/
Theme color: `#F4B731`
Logo (SVG): [Dai-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3936551/Dai-logo.zip)

**Comment by Tomasvrba** [comment]
I actually ended up needing these as well so here they are in 32x32 svg format, white, color and black if that helps:

[dai-svgs.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3949278/dai-svgs.zip)

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
