### ISSUE TITLE
Update Currency REQ

### ISSUE THREAD

**Issue by benjlevesque** [spothq/cryptocurrency-icons#360]
This currency is already referenced but the logo is outdated.

Currency name: Request
Symbol: REQ
Website: https://request.network/
Theme color: `#00e6a0`
Logo (SVG): [request.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3980041/request.zip) & [source](https://github.com/RequestNetwork/Request/blob/master/Hubs/Request%20Logos/Icon/svg/Request_icon_green.svg)

**Comment by tommdn** [comment]
@benjlevesque Looking at this. Color does not seem to match the base colors on the website. Is this part of some design guidelines?

**Comment by benjlevesque** [comment]
Correct. Website uses slightly different colorscheme v.s. brand guidelines. The color should be #00E6A0

**Comment by tommdn** [comment]
Done.
