### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by lukechilds** [spothq/cryptocurrency-icons#371]
Unfortunately the current maintainers of this project have moved on to other things and don't really have time to maintain this anymore.

It's a great resource used by lots of people and I'm happy to transfer this to a new home.

@svenlombaert I know you guys are using this over at @getdelta and expressed interest in maintaining this before (https://github.com/atomiclabs/cryptocurrency-icons/issues/136#issuecomment-396166974). Is that still the case?

If anyone else is interested in maintaining this leave a comment.

**Comment by svenlombaert** [comment]
We moved to our own source of icons, so not really interested anymore. Thanks for asking though!

**Comment by lukechilds** [comment]
Pinging @carsenk @nedsteeg @imnotadeveloper.

**Comment by Paulsky** [comment]
> We don't currently accept contributions for icons as the process for creating them is a bit complicated.

If there are some kind of instructions of the process of the creation the icons, I would love to help out. Please see [MAINTAINING.md](https://github.com/atomiclabs/cryptocurrency-icons/blob/master/MAINTAINING.md)

**Comment by lukechilds** [comment]
@Paulsky There are no official instructions but here is the source file: https://github.com/atomiclabs/cryptocurrency-icons/issues/136#issuecomment-397694533

Any new icons should obviously follow the same style as existing icons but we don't have specific guidelines for this.

**Comment by tommdn** [comment]
Hello @lukechilds, as expressed, we’ve been using your icons in our app Spot [spot-bitcoin.com](https://spot-bitcoin.com) since the beginning and we would love to continue your work!

**Comment by lukechilds** [comment]
@tommdn Do you have a GitHub organisation for Spot I can transfer it to?

**Comment by tommdn** [comment]
@lukechilds you can transfer it here: [spothq](https://github.com/spothq). Thanks!

**Comment by lukechilds** [comment]
@tommdn will do.

You need to delete your fork before it'll let me transfer it over to you.

**Comment by tommdn** [comment]
@lukechilds done.

**Comment by lukechilds** [comment]
@tommdn hmmn, I think you need to add me to @spothq for me to be able to transfer, I'm getting:

>You don’t have the permission to create public repositories on spothq

**Comment by tommdn** [comment]
@lukechilds just added you, let me know!

**Comment by lukechilds** [comment]
@tommdn done!

Thanks so much, I trust you'll take care of it well!
