### ISSUE TITLE
Add DMM: DAI (mDAI)

### ISSUE THREAD

**Issue by coreycaplan3** [spothq/cryptocurrency-icons#374]
Currency name: DMM: DAI
Symbol: mDAI
Website: https://defimoneymarket.com
Theme color: #327ccb
Logo (SVG): https://github.com/defi-money-market-ecosystem/image-assets/blob/master/src/token/DAI/mDAI-square.svg.zip?raw=true

**Comment by tommdn** [comment]
Closed for lack of activity. See #376.
