### ISSUE TITLE
Add DMM: ETH (mETH)

### ISSUE THREAD

**Issue by coreycaplan3** [spothq/cryptocurrency-icons#375]
Currency name: DMM: ETH
Symbol: mETH
Website: https://defimoneymarket.com
Theme color: #327ccb
Logo (SVG): https://github.com/defi-money-market-ecosystem/image-assets/blob/master/src/token/ETH/mETH-square.svg.zip?raw=true

**Comment by tommdn** [comment]
Closed for lack of activity. See #376.
