### ISSUE TITLE
Add DMM: USDC (mUSDC)

### ISSUE THREAD

**Issue by coreycaplan3** [spothq/cryptocurrency-icons#376]
Currency name: DMM: USDC
Symbol: mUSDC
Website: https://defimoneymarket.com
Theme color: #327ccb
Logo (SVG): https://github.com/defi-money-market-ecosystem/image-assets/blob/master/src/token/USDC/mUSDC-square.svg.zip?raw=true

**Comment by tommdn** [comment]
@coreycaplan3 Hello, two points I would like to raise:
• Your SVG file has an image of the underlying asset (at least for USDC). We need fully-vectorized SVG files. You can get the SVG for underlying assets in the repository already so we can keep consistency (I guess you've already taken the rasterized versions here instead).
• It's kinda hard to make something which is easy to read with your icons. Is there a way you could improve what I would call the "bird-to-underlying-asset" ratio? Are you sure we should go forward with how it is now (if yes just update the SVG files)?
Thank you.

**Comment by tommdn** [comment]
Closed for lack of activity.
