### ISSUE TITLE
Pending PRs

### ISSUE THREAD

**Issue by monsieurleberre** [spothq/cryptocurrency-icons#380]
Hello @tommdn, it looks like you have rights to commit to the repo.
Can you please have a look at the pending pull requests?
I thought the repo was going stale but it looks like you can save it ⛑️ !

Thanks a lot, happy to help if you need.
Mine is #363
then I see these too #362 #366 #373 #377

**Comment by tommdn** [comment]
@monsieurleberre Hello! Yes this repo will be saved. I'm currently setting this up to maintain it more easily. Current pull requests will be checked this week.

**Comment by tommdn** [comment]
Done.
