### ISSUE TITLE
Add Aeron (ARNX)

### ISSUE THREAD

**Issue by aeronaero** [spothq/cryptocurrency-icons#387]
* Currency name: Aeron
* Symbol: ARNX
* Website: https://aeron.aero
* Theme color: #436697
* Logo (SVG format): http://aeron.aero/img/ARNX-token-logo.svg
[ARNX-token-logo.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/5160542/ARNX-token-logo.svg.zip)

**Comment by tommdn** [comment]
@aeronaero hello, are you sure about the color? Not sure to find it on the website or logo in the media kit.

**Comment by aeronaero** [comment]
The color seems correct, that is the blue primary image color picked from logo (as example ARNX-token-logo.svg).
Background color should be white. Hope this explains.

**Comment by aeronaero** [comment]
Removed theme color from the issue. Please process the icon.

**Comment by tommdn** [comment]
@aeronaero there should be only one color (look at the other icons from the repository).

Your icon will be flattened to white (or transparent depending on the icon type) but only one color (not a gradient) describing your icon with accuracy is used in the background.
I need you to add the blue color back to the issue so I can design the icon.

**Comment by aeronaero** [comment]
Added the blue color back to the issue: Theme color: #436697
Thank you for clarifications.

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
