### ISSUE TITLE
Add Polkadot (DOT)

### ISSUE THREAD

**Issue by freshpatze** [spothq/cryptocurrency-icons#388]
* Currency name: Polkadot
* Symbol: DOT
* Website: https://polkadot.network
* Theme color: #E6007A
* Logo (SVG): https://polkadot.network/brand-assets/
[SVG.zip](https://github.com/spothq/cryptocurrency-icons/files/5266210/SVG.zip)

**Comment by tommdn** [comment]
![dot](https://user-images.githubusercontent.com/11268305/96517169-b9eabe80-1268-11eb-88cf-4cddcd816865.png)
