### ISSUE TITLE
Add yearn.finance (YFI)

### ISSUE THREAD

**Issue by TheRyanMiller** [spothq/cryptocurrency-icons#389]
* Currency name: yearn.finance
* Symbol: YFI
* Website: https://yearn.finance
* Theme color: #006ae3
* Logo (SVG format):
[yearn-finance-yfi-logo.zip](https://github.com/spothq/cryptocurrency-icons/files/5272482/yearn-finance-yfi-logo.zip)

**Comment by tommdn** [comment]
![yfi](https://user-images.githubusercontent.com/11268305/96517135-aa6b7580-1268-11eb-9b81-ae52c1365f13.png)
