### ISSUE TITLE
Add ALQO (XLQ)

### ISSUE THREAD

**Issue by aldaw** [spothq/cryptocurrency-icons#390]
Add ALQO (XLQ)
* Currency name: ALQO
* Symbol: XLQ
* Website: https://alqo.app/#about
* Theme color: #4D52E9
* Logo (SVG): https://alqo.app/images/logo.svg
[logo.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/5395755/logo.svg.zip)

**Comment by tommdn** [comment]
@aldaw hello. Color does not seem to match with their identity guidelines. Where did you find it?

**Comment by tommdn** [comment]
@aldaw please fill a new issue if still needed. This website is not responding anymore.
