### ISSUE TITLE
Updates to NPM package?

### ISSUE THREAD

**Issue by TheRyanMiller** [spothq/cryptocurrency-icons#393]
I noticed the NPM package version is currently at v0.16.1, and is over a year old.
I think this is the reason that I do not see any of the recent icon additions in my local copy. Do you plan to repackage a new version for NPM anytime soon? If so, I will use that instead of an alternative means of pulling down the latest directly from GitHub. Thanks for the repo and all your efforts!

Apologies, I don't know how to re-label this issue. Should not be a coin request, but not seeing any way to change it.

**Comment by tommdn** [comment]
@TheRyanMiller hello. Yes totally, I got the rights on the NPM package and I plan to automate its update when we have new icons. Will do that soon!

**Comment by tommdn** [comment]
@TheRyanMiller `v0.17.0` is out.
