### ISSUE TITLE
All of them from Coin Market Cap (why are so many missing?)

### ISSUE THREAD

**Issue by oneezy** [spothq/cryptocurrency-icons#396]
Trying to make an app with your icons but we're finding so many crypto coins missing

**Comment by tommdn** [comment]
@oneezy hello. Making a normalized set of icons for all cryptocurrencies is a consuming task and the contributors are doing it on a best effort basis. As far as I know this repository is the largest set of cryptocurrency icons with color normalization, while having the best optical centering. These icons are custom made and based on community requests.

If you are building an app and you do need a lot of icons I would recommend having a placeholder logic for missing icons — as there will always be some.
