### ISSUE TITLE
Update multicollateral DAI icon

### ISSUE THREAD

**Issue by jmynes** [spothq/cryptocurrency-icons#398]
* Currency name: DAI
* Symbol: DAI
* Website: https://makerdao.com/en/
* Theme color: That's a complex question.
  * Officially: #F4B731 (both listed on their website, and present in the zip's Logos > SVGs > Logo_Dai.svg)
  * In the zip, there's a badge icon with a gradient starting at: #FBCC5F
  * Also seen in the wild: #EAB24B, depending on the icon kit used, or if there's a gradient present.
* Logo official kit: https://www.notion.so/Maker-Brand-ac517c82ff9a43089d0db5bb2ee045a4
* Logo flat in a circle, like others in this package (SVG): https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=008
* Coinmarketcap's PNG version: https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png

[Download Maker, MKR and DAI logo kit.zip](https://github.com/spothq/cryptocurrency-icons/files/5700330/Download.Maker.MKR.and.DAI.logo.kit.zip)

Maker has rebranded DAI and changed the logo, though there seem to be a few variants floating around in the wild for their new logo, none are referencing the old one with the Unicode ⬙ symbol any longer:

https://blog.makerdao.com/creating-the-brand-identity-for-the-worlds-first-unbiased-currency-dai/

Unfortunately their badge SVG directory has no flat variant, so I tried my hand at importing the new logo into the same format as the legacy DAI.svg (commit 9a28318)

I'm not well versed in editing SVGs, so there are some details like the viewBox and circle values which differ because I don't know how to properly scale the path:
```
<svg viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg" ><g fill="none"><circle cx="300" cy="300" r="300" fill="#F4B731"/><path d="M477.9 250.5h-35.6c-19.6-54.4-72.3-91.7-141.8-91.7H186.2v91.7h-39.7v32.9h39.7v34.5h-39.7v32.9h39.7v90.6h114.3c68.7 0 121-37 141.1-90.6h36.3v-32.9h-28.3c.7-5.8 1.1-11.8 1.1-17.8v-.8c0-5.4-.3-10.7-.8-15.9H478v-32.9zm-259.7-62.4h82.3c51 0 88.9 25.1 106.4 62.3H218.2v-62.3zm82.3 223.7h-82.3v-61.1h188.5c-17.6 36.6-55.4 61.1-106.2 61.1zm117.1-111c0 5.8-.4 11.5-1.2 17H218.2v-34.5h198.3c.7 5.4 1.1 11 1.1 16.7v.8z" fill="#fff"/></g></svg>
```

**Comment by tommdn** [comment]
We should use `#F4B731` and not the colors from the gradient.

**Comment by tommdn** [comment]
Done in [v0.17.1](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.1).
