### ISSUE TITLE
Add Currency (SUSHI)

### ISSUE THREAD

**Issue by domiha** [spothq/cryptocurrency-icons#404]
* Currency name:  SushiSwap
* Symbol: SUSHI
* Website: https://sushiswapclassic.org/
* Theme color: #000000
* Logo (SVG format): [SUSHI.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/5857210/SUSHI.svg.zip)

**Comment by tommdn** [comment]
@domiha hello. Where did you find the color?

**Comment by domiha** [comment]
@tommdn I've picked the vibrant color of the SVG
