### ISSUE TITLE
Add Synthetix (SNX)

### ISSUE THREAD

**Issue by domiha** [spothq/cryptocurrency-icons#405]
* Currency name: Synthetix
* Symbol: SNX
* Website: https://www.synthetix.io/
* Theme color: #06061b
* Logo (SVG format): [synthetix-network-token-snx-logo.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/5857272/synthetix-network-token-snx-logo.svg.zip)

**Comment by tommdn** [comment]
@domiha hello. Where does the color come from? Is there a press kit?

**Comment by domiha** [comment]
@tommdn I've picked the background color from the website. Sadly there was no press kit.
