### ISSUE TITLE
Add Missing Top 100 Currencies: (okb, aave, cro, sol, snx, ftt, luna, busd, cdai, egld, grt, sushi, ksm, avax, cusdc, cel, ceth, vgx, cake, ftm, xsushi, near, hbtc, rune, hbar, chsb, renbtc, husd, mdx, ust, btmx, flow, zks, ar, rsr)

### ISSUE THREAD

**Issue by jmynes** [spothq/cryptocurrency-icons#410]
* Currency names: okb, aave, cro, sol, snx, ftt, luna, busd, cdai, egld, grt, sushi, ksm, avax, cusdc, cel, ceth, vgx, cake, ftm, xsushi, near, hbtc, rune, hbar, chsb, renbtc, husd, mdx, ust, btmx, flow, zks, ar, rsr 
* Symbol: Various
* Website: Various
* Theme color: Various
* Logo (SVG format): Various

Have you considered scraping icons from an aggregator such as 1inch?:
https://docs.1inch.exchange/api/tokens

**Comment by tommdn** [comment]
@jmynes hello.
The cryptocurrency ecosystem is using the icons from this repository to present assets without biases. We craft them carefully, they are custom made so there is a visual unity, are optically centered and we here aim for quality.
Please file one request per icon. Your request, coupled with the question about scraping, reflects at worse manifest condescension — at best a misunderstanding of the spirit and purpose of this repository.

**Comment by tommdn** [comment]
@jmynes hello.
The cryptocurrency ecosystem is using the icons from this repository to present assets without biases. We craft them carefully, they are custom made so there is a visual unity, they are optically centered and we here aim for quality.
Please file one request per icon. Your request, coupled with the question about scraping, reflects at worse manifest condescension — at best a misunderstanding of the spirit and purpose of this repository.
