### ISSUE TITLE
Add Bitcoin Fils (BTCFILS) / Digital Fils (FILS)

### ISSUE THREAD

**Issue by BTCfils** [spothq/cryptocurrency-icons#416]
* Currency name: Bitcoin Fils / Digital Fils
* Symbol: BTCFILS /FILS
* Website: btcfils.com  / digitalfils.com
* Theme color: 
* Logo (SVG format): 
* Could you please verify my slp tokens:
Digital Fils : ID a7af0ffe54a50b7777a27d7ad3c9d077f710a3bec89a6b5eb4425023a546d5b0
Bitcoin Fils : ID cf8e566d2bf49ab0f52d83c1db6e0f7785ee625d6cb9891f77f4401a5b3816f2

**Comment by BTCfils** [comment]
Could you please verify my tokens BTCfils and Digital Fils.

**Comment by tommdn** [comment]
Hello @BTCfils please include SVG icons and fill the issue correctly.

**Comment by tommdn** [comment]
Hello @BTCfils please fill a new issue with the correct information if still needed.
