### ISSUE TITLE
Better way to access these?

### ISSUE THREAD

**Issue by jfgrissom** [spothq/cryptocurrency-icons#421]
I've got a list of items I'm iterating over and I'm accessing these using something like this.

``` 
let assetPath: string
try {
  assetPath = require(`cryptocurrency-icons/svg/color/${currency}.svg`)
} catch {
  assetPath = require('cryptocurrency-icons/svg/color/generic.svg')
}
<img src={assetPath} />
```
This causes lots of ESLint and TS compiler issues (I've gotten it to work but this require outside of global scope feels unclean).

It seems like there should be a smarter way that I'm missing.

Can someone share that way with me.
:D

**Comment by jfgrissom** [comment]
If someone can explain this to me I'll be happy to submit the PR with changes to the README (or whatever other changes are required).

**Comment by rafalbromirski** [comment]
You can try to import manifest and try to extract info from there

```
import assetsManifest from 'cryptocurrency-icons/manifest.json';
```

It's an array so you can easily use `some()` or `find()` methods
