### ISSUE TITLE
Add Emblem (EMB)

### ISSUE THREAD

**Issue by cw-blockcollider** [spothq/cryptocurrency-icons#429]
* Currency name: Emblem
* Symbol: EMB
* Website: https://emb.overline.network/
* Theme color: #f6c054
* Logo (SVG format): [EMB_Logo.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/6437543/EMB_Logo.svg.zip)

**Comment by cw-blockcollider** [comment]
@tommdn Want to make sure there's nothing else we need to add here. Here is a link to the SVG logo file that is not zipped: https://files.readme.io/bb3b2c6-EMB-Color.svg

**Comment by tommdn** [comment]
@cw-blockcollider we're good.
