### ISSUE TITLE
Add Stacks (STX)

### ISSUE THREAD

**Issue by kyranjamie** [spothq/cryptocurrency-icons#430]
![image](https://user-images.githubusercontent.com/1618764/117638153-d73e9600-b182-11eb-8ad8-39b62e9b242b.png)

* Currency name: Stacks
* Symbol: `STX`
* Website: https://www.stacks.co/
* Theme color: `#5546FF`
* Logo (SVG format): [stx-icons.zip](https://github.com/spothq/cryptocurrency-icons/files/6451086/stx-icons.zip)

**Note**: The `STX` symbol currently refers to the defunkt [Stox token](https://coinmarketcap.com/currencies/stox/), rank `#1768`. 
This ticker is now widely used to refer to the [Stacks token](https://coinmarketcap.com/currencies/stacks/) rank `#67` on Coinmarketcap as well as various exchanges: Binance, Kucoin, Okex etc. I'd suggest this old project is removed, or renamed to `STOX`.

This change is important, as Ledger Live now utilises this repository for their icons.

### Icons

<details>
<summary>White circle</summary>

```
<svg width="812" height="812" viewBox="0 0 812 812" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M406 812C630.228 812 812 630.228 812 406C812 181.772 630.228 0 406 0C181.772 0 0 181.772 0 406C0 630.228 181.772 812 406 812ZM583 394.451V351.353H477.186L551.494 239H495.317L405.851 374.536L316.683 239H260.506L334.814 351.353H229V394.748H583V394.451ZM550.305 593L475.106 479.161H583V436.36H229V479.458H336.894L261.695 593H317.574L405.851 459.247L494.128 593H550.305Z" fill="white"/>
</svg>
```
</details>

<details>
<summary>Black circle</summary>

```
<svg width="812" height="812" viewBox="0 0 812 812" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M406 812C630.228 812 812 630.228 812 406C812 181.772 630.228 0 406 0C181.772 0 0 181.772 0 406C0 630.228 181.772 812 406 812ZM583 394.451V351.353H477.186L551.494 239H495.317L405.851 374.536L316.683 239H260.506L334.814 351.353H229V394.748H583V394.451ZM550.305 593L475.106 479.161H583V436.36H229V479.458H336.894L261.695 593H317.574L405.851 459.247L494.128 593H550.305Z" fill="black"/>
</svg>
```
</details>

<details>
<summary>Brand colour circle</summary>

```
<svg width="812" height="812" viewBox="0 0 812 812" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M406 812C630.228 812 812 630.228 812 406C812 181.772 630.228 0 406 0C181.772 0 0 181.772 0 406C0 630.228 181.772 812 406 812ZM583 394.451V351.353H477.186L551.494 239H495.317L405.851 374.536L316.683 239H260.506L334.814 351.353H229V394.748H583V394.451ZM550.305 593L475.106 479.161H583V436.36H229V479.458H336.894L261.695 593H317.574L405.851 459.247L494.128 593H550.305Z" fill="#5546FF"/>
</svg>
```
</details>

**Comment by tommdn** [comment]
@kyranjamie hello, where did you get the color from?

**Comment by tommdn** [comment]
Thanks, icon is live in release [v0.17.2](https://github.com/spothq/cryptocurrency-icons/releases/tag/v0.17.2).
