### ISSUE TITLE
Add Internet Computer (ICP)

### ISSUE THREAD

**Issue by alphapuggle** [spothq/cryptocurrency-icons#438]
* Currency name:  Internet Computer
* Symbol: ICP
* Website: https://dfinity.org
* Theme color: #FAB13B [(From here)](https://dfinity.frontify.com/d/u95VmXksof7q/dfinity-style-guide#/basics/colors)
* Logo (SVG format): [Drive Link](https://drive.google.com/file/d/1-xdZFK8ov9QNGr9vmWyji4Oy5YQuObF0/view?usp=sharing) [(From Here)](https://dfinity.org/media/)

**Comment by tommdn** [comment]
@alphapuggle I think we should go with the black color as the original logo is multicolored.
