### ISSUE TITLE
Add Currency DREP

### ISSUE THREAD

**Issue by DroidBoyJr** [spothq/cryptocurrency-icons#439]
* Currency name: Drep
* Symbol: DREP
* Website: https://www.drep.org/
* Theme color: #fbd42c

[image2vector.svg.zip](https://github.com/spothq/cryptocurrency-icons/files/6580435/image2vector.svg.zip)

**Comment by DroidBoyJr** [comment]
Thank yo for the amazing collection

**Comment by tommdn** [comment]
@DroidBoyJr hello — please link a proper SVG and not a vectorized image.

**Comment by tommdn** [comment]
Hello, please file a new issue with all the information if you still need this icon. Thanks.
