### ISSUE TITLE
Icons without background

### ISSUE THREAD

**Issue by toine2one** [spothq/cryptocurrency-icons#441]
Hi !

First of all, we love this library of icons and would like to compliment you on this very complete set.

We plan to use the icons for our blockchain-based (game) project.
For optimization reasons It would be great if we have the icons without any background.

Is there any kind of source/PSD file available?

Hope to hear from you.

P.S. Sorry if this is not the best way to raise this question.

**Comment by tommdn** [comment]
Hello, and thank you on behalf of all the contributors. I'm (modestly) trying to take up the torch on this — and am committed to ensure this repository continues to set the standard in the field.

I assume you are talking about the circles behind the icons. I'm not sure I understand what you mean by "optimisation reasons" exactly.

There exist no version of the icons without the circles. You can find some of the originals in the corresponding folder, but they lack the sole interests of the repository: sizing uniformity and optical centering.

I think you can remove the circles with a little script though. Those are SVG files after all.
