### ISSUE TITLE
Add Frenchie (FREN)

### ISSUE THREAD

**Issue by FrenchieNetwork** [spothq/cryptocurrency-icons#443]
* Currency name:  Frenchie Network
* Symbol: FREN
* Website: https://frenchie.tech
* Theme color: 
* Logo (SVG format):

**Comment by tommdn** [comment]
Hello @FrenchieNetwork, please fill the form completely.

**Comment by tommdn** [comment]
Hello, please file a new issue if you still need this icon with all the information. Thanks.
