### ISSUE TITLE
Add HashBit Blockchain (HBIT)

### ISSUE THREAD

**Issue by HashBitorg** [spothq/cryptocurrency-icons#449]
Currency name: HashBit Blockchain
Symbol: SPACEHBIT
Website: https://chain.hashbit.org/
Theme color: #0971FE
Logo (SVG format): HBIT_COIN_LOGO_GOLD.zip
[HBIT_COIN_LOGO_GOLD.zip](https://github.com/spothq/cryptocurrency-icons/files/6742995/HBIT_COIN_LOGO_GOLD.zip)

**Comment by tommdn** [comment]
@HashBitorg hello. Can I remove the text "Hashbit" at the center of the logo? It is not readable when I export the icons. Example below.

<img src="https://user-images.githubusercontent.com/11268305/124948157-bd012700-e010-11eb-80c3-5511b58c3ddc.png" width="30" height="30">

**Comment by HashBitorg** [comment]
> @HashBitorg hello. Can I remove the text "Hashbit" at the center of the logo? It is not readable when I export the icons. Example below.
> 
> <img alt="" width="30" height="30" src="https://user-images.githubusercontent.com/11268305/124948157-bd012700-e010-11eb-80c3-5511b58c3ddc.png">

Yes no problem
