### ISSUE TITLE
Add Support for BSC Tokens

### ISSUE THREAD

**Issue by Ncookiez** [spothq/cryptocurrency-icons#455]
Any chance of getting token icons for tokens in other chains such as BSC or Polygon?

Thanks for the awesome project regardless :)

**Comment by tommdn** [comment]
@Ncookiez totally, please file the corresponding issues and if we have all the elements we will add the icons.

Thanks!

**Comment by Ncookiez** [comment]
The reason I ask is because there might need to be some workarounds - for example, on BSC you have a BEP-20 token called AUTO, but there is a different ERC-20 token also called AUTO, and they have different logos and are completely different projects.

Would submitting an issue for such a token be ok or would it be too complicated to implement?

**Comment by tommdn** [comment]
Please file an issue for each and we can look at it. We can start with adding a symbol suffix for the duplicates.

**Comment by tommdn** [comment]
Please file an issue for each and we can look at it. We can start by adding a symbol suffix for the duplicates.
