### ISSUE TITLE
Add Polkadot (DOT)

### ISSUE THREAD

**Issue by antonnag** [spothq/cryptocurrency-icons#464]
* Currency name: Polkadot
* Symbol: DOT
* Website: https://polkadot.network/
* Theme color: #ff9500
* Logo (SVG): https://cryptologos.cc/logos/polkadot-new-dot-logo.svg?v=013

**Comment by syeo66** [comment]
Hm, did you actually look for it?
https://github.com/spothq/cryptocurrency-icons/blob/master/svg/icon/dot.svg

**Comment by tommdn** [comment]
@antonnag hello. You are wasting @syeo66 time – and mine.

**Comment by tommdn** [comment]
@antonnag hello. You are wasting @syeo66 time — and mine.

**Comment by antonnag** [comment]
Hi all - i checked both icons on your page.
now i realized your repo is used by both servers ? 

https://cryptoicons.org/ <https://cryptoicons.org/> --> i guess this one is the legacy one , here i looked for the icons which i didn't find.
http://cryptoicons.co/ <http://cryptoicons.co/>   --> this one seems to be the new version

Anyways thank you for the effort !!!
