### ISSUE TITLE
Add Uniswap (UNI)

### ISSUE THREAD

**Issue by antonnag** [spothq/cryptocurrency-icons#465]
* Currency name: Uniswap
* Symbol: UNI
* Website: https://uniswap.org/
* Theme color: #ff9500
* Logo (SVG): https://cryptologos.cc/logos/uniswap-uni-logo.svg?v=013

**Comment by syeo66** [comment]
It is there:
https://github.com/spothq/cryptocurrency-icons/blob/master/svg/icon/uni.svg
