### ISSUE TITLE
Add NewWorldDisorder (NWD)

### ISSUE THREAD

**Issue by atlantiswarrior** [spothq/cryptocurrency-icons#475]
Currency name:
    New World Disorder
    Symbol:
    NWD
    Website:
    Currency name:
    Terra
    Symbol:
    NWD
    Website:
    https://github.com/atlantiswarrior/newworlddisorder
    Theme color:
    #FFFFFF 
    Logo (SVG format):
    https://github.com/atlantiswarrior/docs/blob/main/copy.svg

**Comment by tommdn** [comment]
@atlantiswarrior the repository you linked is empty. Do you have another website link?

**Comment by tommdn** [comment]
@atlantiswarrior Please create a new issue with the corresponding information if needed.
