### ISSUE TITLE
Add Currency (LUNA)

### ISSUE THREAD

**Issue by fasterv410** [spothq/cryptocurrency-icons#494]
* Currency name: Terra
* Symbol: LUNA
* Website: https://coinmarketcap.com/currencies/terra-luna/
* Theme color: #ffd83d, #172854
* Logo (SVG): https://cryptologos.cc/logos/terra-luna-luna-logo.svg?v=022

**Comment by tommdn** [comment]
@fasterv410 hello, this is the Terra Classic (LUNC) logo. Can you open another issue with the correct logo?
Thanks!
