### ISSUE TITLE
Add Terra LUNA and Avalanche AVAX logos, please

### ISSUE THREAD

**Issue by adminoid** [spothq/cryptocurrency-icons#502]
Add Terra (LUNA) <https://cryptologos.cc/logos/terra-luna-luna-logo.svg?v=022>
Add Avalanche (AVAX) <https://cryptologos.cc/logos/avalanche-avax-logo.svg?v=022>

**Comment by tommdn** [comment]
@adminoid hello — regarding Terra this is the Terra Classic (LUNC) logo. Can you please create another issue with the correct format?
AVAX comes in the next batch.
