### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by syeo66** [spothq/cryptocurrency-icons#507]
There have been no updates to the repo since January and no updates of the icons since almost a year.

Is it still maintained? Could maybe someone else take over or help out?
Thanks for letting us know.

**Comment by syeo66** [comment]
No answer... I guess this answers my question.

**Comment by tommdn** [comment]
@syeo66 hello! Yes it is. Sorry for the lack of answer. :)
Next batch should be ready soon.
