### ISSUE TITLE
Can you add AVAX icon ?

### ISSUE THREAD

**Issue by Akm-mt** [spothq/cryptocurrency-icons#512]
* Currency name:  Avalanche
* Symbol: AVAX
* Website: https://www.avax.network/
* Theme color: black
* Logo (SVG format): https://assets-global.website-files.com/6059b554e81c705f9dd2dd32/628692ef405f676b64a3fd20_avalanche-iso.svg

**Comment by syeo66** [comment]
Did you check if there is already a request for AVAX?

**Comment by Akm-mt** [comment]
Ok sry, i will delete my issue !

**Comment by tommdn** [comment]
@Akm-mt hello. AVAX is in.
